<?php

/**
 * @file
 * Contains gen_modul.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gen_modul_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gen_modul module.
    case 'help.page.gen_modul':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
