themekey.themekey_rule.*:
  type: config_entity
  label: 'ThemeKey Rule config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    property:
      type: string
      label: 'Property'
    key:
      type: string
      label: 'Key'
    operator:
      type: string
      label: 'Operator'
    value:
      type: string
      label: 'Value'
    theme:
      type: string
      label: 'Theme'
    comment:
      type: string
      label: 'Comment'
      translatable: true
