# Schema for the configuration files of the node module.

# @todo Review Entityform D7 settings to make sure all were duplicated.

eform.type.*:
  type: config_entity
  label: 'EForm type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    form_title:
      type: string
      label: 'Title for form.'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    form_status:
      type: string
      label: 'Form Status'
    resubmit_action:
      type: string
      label: 'Resubmit Action'
    disallow_text:
          type: mapping
          label: 'Disallow Text'
          mapping:
            format:
              type: string
              label: 'Format'
            value:
              type: string
              label: 'Value'
    preview_page:
      type: boolean
      label: 'Preview Page'
    submission_page_title:
      type: string
      label: 'Submission Page Title'
    submission_text:
      type: mapping
      label: 'Submission Text'
      mapping:
        format:
          type: string
          label: 'Format'
        value:
          type: string
          label: 'Value'
    submission_text:
      type: mapping
      label: 'Submission Text'
      mapping:
        format:
          type: string
          label: 'Format'
        value:
          type: string
          label: 'Value'
    submission_show_submitted:
      type: boolean
      label: 'Show submission information'
    draftable:
      type: boolean
      label: 'Draftable'
    admin_submissions_view:
      type: string
      label: 'Submission Admin View'
    user_submissions_view:
      type: string
      label: 'Submission User View'
# Config object for EForm Type defaults
# This should follow the same format as eform.type.* but without all settings.
eform.type_defaults:
  type: config_object
  label: 'EForm Type Defaults'
  mapping:
    form_title:
      type: string
      label: 'Title for form.'
    form_status:
      type: string
      label: 'Form status'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    resubmit_action:
      type: string
      label: 'Resubmit Action'
    disallow_text:
      type: mapping
      label: 'Disallow Text'
      mapping:
        format:
          type: string
          label: 'Format'
        value:
          type: string
          label: 'Value'
    roles:
      type: sequence
      sequence:
        type: string
        label: 'Roles'
    preview_page:
      type: boolean
      label: 'Preview Page'
    submission_page_title:
      type: string
      label: 'Submission Page Title'
    submission_text:
      type: mapping
      label: 'Submission Text'
      mapping:
        format:
          type: string
          label: 'Format'
        value:
          type: string
          label: 'Value'
    submission_show_submitted:
      type: boolean
      label: 'Show submission information'
    draftable:
      type: boolean
      label: 'Draftable'
    admin_submissions_view:
      type: string
      label: 'Submission Admin View'
    user_submissions_view:
      type: string
      label: 'Submission User View'

action.configuration.eform_submission_delete_action:
  type: action_configuration_default
  label: 'Delete eForm submission.'