name: Active configuration file handling.
type: module
description: 'Allows you to specify an active file directory to save current configuration.'
package: Configuration
# version: VERSION
# core: 8.x
configure: config_files.settings

# Information added by Drupal.org packaging script on 2016-04-25
version: '8.x-1.0-alpha3+1-dev'
core: '8.x'
project: 'config_tools'
datestamp: 1461604648
