services:
  config_sync.initializer:
    class: Drupal\config_sync\ConfigSyncInitializer
    arguments:
     - '@config_provider.collector'
     - '@config_sync.snapshotter'
     - '@config.storage'
     - '@config_sync.snapshot_extension_storage'
     - '@config_sync.merged_storage'
     - '@config.manager'
  config_sync.lister:
    class: Drupal\config_sync\ConfigSyncLister
    arguments:
     - '@config_provider.collector'
     - '@config.storage'
     - '@config_sync.snapshot_extension_storage'
     - '@config.manager'
  config_sync.snapshot_active_storage:
    class: Drupal\Core\Config\DatabaseStorage
    arguments:
     - '@database'
     - 'config_sync_snapshot_active'
    tags:
      - { name: backend_overridable }
  config_sync.snapshot_extension_storage:
    class: Drupal\Core\Config\DatabaseStorage
    arguments:
     - '@database'
     - 'config_sync_snapshot_extension'
    tags:
      - { name: backend_overridable }
  config_sync.merged_storage:
    class: Drupal\Core\Config\DatabaseStorage
    arguments:
     - '@database'
     - 'config_sync_merged'
    tags:
      - { name: backend_overridable }
  config_sync.snapshotter:
    class: Drupal\config_sync\ConfigSyncSnapshotter
    arguments:
     - '@config_provider.collector'
     - '@config.storage'
     - '@config_sync.snapshot_extension_storage'
     - '@config_sync.snapshot_active_storage'
     - '@config.manager'
