<?php

/**
 * Implements hook_theme().
 */
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
	// Main module help for the block module.
	case 'help.page.hello':
	  return '<p>' . t('test aide hello') . '</p>';
  }
}

function hello_cron() {
	drupal_set_message("hello cron","error");
}

function hello_user_login($account) {
  //dpm($account);
  //kint($account);
  $name = $account->getAccountName();
  drupal_set_message(t('Bienvenue chez Hello <strong>@name</strong>', array('@name' => $name)));
}

/**
 * Implements hook_node_update_index().
 */
use Drupal\Core\Database\Database;

function hello_node_update(\Drupal\node\NodeInterface $node)
{
    $db = \Drupal::database();
    $db->insert('hello_node_history')->fields(
        array(
            'nid' => $node->id(),
            'uid' =>  \Drupal::currentUser()->id(),
            'update_time' => time()
        )
    )->execute();
}

/**
 * Implements hook_page_attachments().
 */
function hello_page_attachments(array &$attachments)
{
    $attachments['#attached']['library'][] = 'hello/bloc';
}
/**
 * Implements hook_preprocess_HOOK().
 */
function hello_preprocess_block(&$variables)
{
    //kint($variables);
    //$region = $variables['region'];
    $color = \Drupal::config('hello.config')->get('color');
    $tabclass = array('green' => 'color-vert', 'blue' => 'color-blue', 'orange' => 'color-orange');
    $variables['attributes']['class'][] = $tabclass[$color];
}

/**
 * Implements hook_theme().
 */
function hello_theme($existing, $type, $theme, $path)
{
    return array(
        'hello-node-history' => array(
            'template' => 'hello-node-history',
            'variables' => array('node' => NULL, 'count' => NULL)
        )
    );
}

/**
 * Implements hook_form_alter().
 */
function hello_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if ($form_id == 'contact_message_feedback_form') {
        $form['telefon'] = array(
            '#type' => 'tel',
            '#title' => 'Téléphone',
            '#description' => t('Enter phone number'),
            '#size' => '20',
            '#maxlength' => '20',
            '#attributes' => array('placeholder' => 'Your phone number'),
        );
        $form['subject']['#access'] = FALSE;
        $form['actions']['submit']['#value'] = "send message now";
        array_unshift($form['actions']['submit']['#submit'], 'my_function_before');
        return $form;
    }
}

function my_function_before(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
    //$phone = $form_state->getValue('telefon');
    //$form_state->setValue('message', $phone);
}

/**
 * Implements hook_mail_alter().
 */
function hello_mail_alter(&$message)
{
    //if ($message['id'] == 'contact_page_mail') {
    //    $message['body'][] = $message['params']['telefon'];
    //}
}